### ISSUE TITLE
data_english missing

### ISSUE THREAD

**Issue by mattilyra** [PrekshaNema25/StructuredData_To_Descriptions#2]
the data directory for english training data is missing from the repo

**Comment by PrekshaNema25** [comment]
Please refer to the original repo to extract the data for English:
https://github.com/DavidGrangier/wikipedia-biography-dataset

**Comment by shefalilodha** [comment]
> Please refer to the original repo to extract the data for English:
> https://github.com/DavidGrangier/wikipedia-biography-dataset
 even though i downloaded directly, the data_english folder dosnt not have all the file, such as train_summary when manually downloading from the link

**Comment by parajain** [comment]
Please download the processed version from the following [link](https://ibm.box.com/s/9psqggbo1nftzj5fnrxh99r8i7akl6g8)
We will update the repo with the script soon.
